version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - run:
          name: Update npm version
          command: sudo npm install -g npm@10.8.2
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build  # This builds the React app for production
      - run:
          name: Run tests (watch false)
          command: npm run test -- --watch=false
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main